# The URL the site will be built for
base_url = "https://codeshow.com.br"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

default_language = 'pt'

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "dinkleberg"

paginate_by = 5

generate_rss = true

generate_categories_pages = true
generate_tags_pages = true

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
blog_logo="/codeshow_logo.png" #will appear on top header
blog_title="CodeShow" #will appear on top header after logo

## i18n words
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categorias"
label_category = "Categoria"
label_relative_posts = "Postagens Relacionadas"
label_next = "PrÃ³xima"
label_previous = "Anterior"
label_page = "PÃ¡gina"
label_of = "de"
label_minutes = "minutos"

og_image="/codeshow_py.png" # Image that will appear on social media
og_alt_image="/hands_in_show.png" # Alt for og_image
og_site_name="CodeShow" # Site Name for Open Graphic
keywords="programaÃ§Ã£o, desenvolvimento, programador, python, flask, rust, qualidade de software, engenharia de software" # Keywords for SEO

educational_use="knowledge share" # OPTIONAL
copyright_year="2019" # OPTIONAL

#fb_app_id="???" # OPTIONAL, Facebook App Id to help in metrics
twitter_username="@rochacbruno" # OPTIONAL, Twitter User to help with metrics

## Sidebar automatic links
sidebar = [
    {name = "Links:", urls=[
        {name="ğŸ“º Youtube", url="https://youtube.com/CodeShowBrunoRocha", target="_blank"},
        {name="ğŸ™ Podcast", url="https://anchor.fm/codeshow", target="_blank"},
        {name="ğŸ“¸ Instagram", url="https://instagram.com/codeshowbr", target="_blank"},
        {name="ğŸ¤ Twitter", url="https://twitter.com/rochacbruno", target="_blank"},
        {name="ğŸ’¬ Telegram", url="https://t.me/codeshowbr", target="_blank"},
        {name="ğŸ’» Github", url="https://github.com/codeshow", target="_blank"},
        {name="ğŸ’µ Apoie", url="https://apoia.se/codeshow", target="_blank"},
    ]},
    {name = "ConteÃºdo:", urls=[
        {name="ğŸ—ƒ Categorias", url="/categories", target="_self"},
        {name="ğŸ· Tags", url="/tags", target="_self"},
        {name="ğŸ–¼ Sobre", url="/about", target="_self"},
    ]},
]

top_image = {path = '../static/top_banner.png', width=1015, height=250, op='fill', url='https://www.youtube.com/c/CodeShowBrunoRocha?sub_confirmation=1', target="_blank"}

authors = {rochacbruno={name='Bruno Rocha', avatar='https://avatars0.githubusercontent.com/u/458654?s=200&v=4'}}
